"""digital twin daily checkins and consents

Revision ID: 15916a980856
Revises: ccb3628ef287
Create Date: 2026-09-28 23:01:51.817543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15916a980856'
down_revision: Union[str, Sequence[str], None] = 'ccb3628ef287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index('uq_consents_active', 'consents', ['patient_id', 'purpose'], unique=True, postgresql_where=sa.text('withdrawn_at IS NULL'))
    op.create_table('daily_checkins',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('pain', sa.SmallInteger(), nullable=False),
    sa.Column('stiffness', sa.SmallInteger(), nullable=False),
    sa.Column('swelling', sa.Enum('none', 'mild', 'moderate', 'severe', name='swelling', native_enum=False, length=24), nullable=False),
    sa.Column('sleep', sa.Enum('good', 'ok', 'poor', name='sleep', native_enum=False, length=24), nullable=False),
    sa.Column('exercises', sa.Enum('all', 'some', 'none', name='exercisesdone', native_enum=False, length=24), nullable=False),
    sa.Column('red_flags', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('app', 'web', 'whatsapp', name='checkinsource', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_daily_checkins_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_daily_checkins_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checkins')),
    sa.UniqueConstraint('patient_id', 'day', name=op.f('uq_daily_checkins_patient_id'))
    )
    op.create_index(op.f('ix_daily_checkins_care_plan_id'), 'daily_checkins', ['care_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_checkins_care_plan_id'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.drop_index('uq_consents_active', table_name='consents', postgresql_where=sa.text('withdrawn_at IS NULL'))
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
