"""invoice payments and larger clinic logo

Revision ID: a8abe38c6ee1
Revises: 937890fbc65d
Create Date: 2026-09-25 14:51:31.195403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8abe38c6ee1'
down_revision: Union[str, Sequence[str], None] = '937890fbc65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('invoices', sa.Column('appointment_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_paid_at'), 'invoices', ['paid_at'], unique=False)
    op.create_unique_constraint(op.f('uq_invoices_appointment_id'), 'invoices', ['appointment_id'])
    op.create_foreign_key(op.f('fk_invoices_created_by_users'), 'invoices', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_invoices_appointment_id_appointments'), 'invoices', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoices_appointment_id_appointments'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_created_by_users'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('uq_invoices_appointment_id'), 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_paid_at'), table_name='invoices')
    op.drop_column('invoices', 'created_by')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'appointment_id')
    op.alter_column('clinics', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
