"""initial schema

Revision ID: c5bb115cb21e
Revises: 
Create Date: 2026-09-25 12:57:43.085822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5bb115cb21e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_tips',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('publish_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_tips')),
    sa.UniqueConstraint('publish_on', name=op.f('uq_health_tips_publish_on'))
    )
    op.create_table('otp_requests',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Enum('login', name='otppurpose', native_enum=False, length=24), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_requests'))
    )
    op.create_index(op.f('ix_otp_requests_phone'), 'otp_requests', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('patient', 'physio', 'staff', 'super_admin', name='userrole', native_enum=False, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_clinic_id'), 'audit_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_table('clinics',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('platform_fee_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_clinics_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics')),
    sa.UniqueConstraint('slug', name=op.f('uq_clinics_slug'))
    )
    op.create_index(op.f('ix_clinics_owner_user_id'), 'clinics', ['owner_user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expo_token', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('expo_token', name=op.f('uq_device_tokens_expo_token'))
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F', 'O', name='sex', native_enum=False, length=2), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('best_streak_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patients_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patients_user_id'))
    )
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('physio_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('qualification', sa.String(length=120), nullable=True),
    sa.Column('registration_no', sa.String(length=60), nullable=False),
    sa.Column('council', sa.String(length=80), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('college', sa.String(length=160), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('specializations', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('offers_in_clinic', sa.Boolean(), nullable=False),
    sa.Column('offers_online', sa.Boolean(), nullable=False),
    sa.Column('fee_in_clinic_paise', sa.Integer(), nullable=True),
    sa.Column('fee_online_paise', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_physio_profiles_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_physio_profiles_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physio_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_physio_profiles_user_id'))
    )
    op.create_index(op.f('ix_physio_profiles_verification_status'), 'physio_profiles', ['verification_status'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_platform_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hours', sa.String(length=120), nullable=True),
    sa.Column('therapy_rooms', sa.Integer(), nullable=False),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_branches_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], name=op.f('fk_branches_lead_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_city'), 'branches', ['city'], unique=False)
    op.create_index(op.f('ix_branches_clinic_id'), 'branches', ['clinic_id'], unique=False)
    op.create_table('clinic_patients',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('primary_physio_id', sa.UUID(), nullable=True),
    sa.Column('mrn', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('active', 'discharged', name='clinicpatientstatus', native_enum=False, length=24), nullable=False),
    sa.Column('first_visit_on', sa.Date(), nullable=True),
    sa.Column('last_visit_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_patients_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinic_patients_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_physio_id'], ['users.id'], name=op.f('fk_clinic_patients_primary_physio_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_patients')),
    sa.UniqueConstraint('clinic_id', 'patient_id', name=op.f('uq_clinic_patients_clinic_id'))
    )
    op.create_index(op.f('ix_clinic_patients_clinic_id'), 'clinic_patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_patients_patient_id'), 'clinic_patients', ['patient_id'], unique=False)
    op.create_table('exercises',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('body_region', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('strength', 'mobility', 'stretch', 'balance', 'proprioception', 'endurance', 'breathing', 'functional', name='exercisecategory', native_enum=False, length=24), nullable=False),
    sa.Column('position', sa.Enum('standing', 'sitting', 'supine', 'prone', 'side_lying', 'quadruped', 'kneeling', name='exerciseposition', native_enum=False, length=24), nullable=True),
    sa.Column('equipment', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('dose_unit', sa.Enum('reps', 'seconds', name='doseunit', native_enum=False, length=24), nullable=False),
    sa.Column('default_sets', sa.SmallInteger(), nullable=False),
    sa.Column('default_reps', sa.SmallInteger(), nullable=True),
    sa.Column('default_hold_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('default_rest_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cues', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('source', sa.Enum('platform', 'clinic', name='exercisesource', native_enum=False, length=24), nullable=False),
    sa.Column('owner_clinic_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'clinic', name='exercisevisibility', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'published', 'rejected', name='exercisestatus', native_enum=False, length=24), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(body_region, '') || ' ' || coalesce(category, '') || ' ' || coalesce(cues, ''))", persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exercises_created_by_users')),
    sa.ForeignKeyConstraint(['owner_clinic_id'], ['clinics.id'], name=op.f('fk_exercises_owner_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_exercises_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('slug', name=op.f('uq_exercises_slug'))
    )
    op.create_index(op.f('ix_exercises_body_region'), 'exercises', ['body_region'], unique=False)
    op.create_index(op.f('ix_exercises_owner_clinic_id'), 'exercises', ['owner_clinic_id'], unique=False)
    op.create_index('ix_exercises_search', 'exercises', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_exercises_status'), 'exercises', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('purpose', sa.Enum('appointment', 'invoice', 'subscription', name='paymentpurpose', native_enum=False, length=24), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('platform_fee_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'refunded', name='paymentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=40), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=40), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_payments_clinic_id_clinics')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_payments_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('uq_payments_razorpay_order_id')),
    sa.UniqueConstraint('razorpay_payment_id', name=op.f('uq_payments_razorpay_payment_id'))
    )
    op.create_index(op.f('ix_payments_clinic_id'), 'payments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_purpose'), 'payments', ['purpose'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('points_ledger',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_points_ledger_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points_ledger'))
    )
    op.create_index(op.f('ix_points_ledger_patient_id'), 'points_ledger', ['patient_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('monthly', 'yearly', name='subscriptionplan', native_enum=False, length=24), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'overdue', 'cancelled', name='subscriptionstatus', native_enum=False, length=24), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_subscriptions_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('clinic_id', name=op.f('uq_subscriptions_clinic_id'))
    )
    op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.Enum('in_clinic', 'online', name='consultmode', native_enum=False, length=24), nullable=False),
    sa.Column('kind', sa.Enum('initial', 'follow_up', name='appointmentkind', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'checked_in', 'completed', 'cancelled', 'no_show', name='appointmentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('source', sa.Enum('patient_app', 'reception', name='appointmentsource', native_enum=False, length=24), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('referral_source', sa.String(length=60), nullable=True),
    sa.Column('fee_paise', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('video_room_id', sa.String(length=120), nullable=True),
    sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_2h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_appointments_branch_id_branches')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_appointments_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_appointments_payment_id_payments')),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_appointments_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_physio_starts', 'appointments', ['physio_user_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('availabilities',
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_availabilities_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_availabilities_physio_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilities'))
    )
    op.create_index(op.f('ix_availabilities_physio_user_id'), 'availabilities', ['physio_user_id'], unique=False)
    op.create_table('care_plans',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.String(length=160), nullable=False),
    sa.Column('condition_detail', sa.String(length=200), nullable=True),
    sa.Column('goal', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sessions_planned', sa.SmallInteger(), nullable=True),
    sa.Column('starts_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='careplanstatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_care_plans_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_care_plans_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_plans'))
    )
    op.create_index(op.f('ix_care_plans_clinic_patient_id'), 'care_plans', ['clinic_patient_id'], unique=False)
    op.create_index(op.f('ix_care_plans_status'), 'care_plans', ['status'], unique=False)
    op.create_table('clinic_members',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'physio', 'staff', name='membershiprole', native_enum=False, length=24), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('monthly_salary_paise', sa.Integer(), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_clinic_members_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_clinic_members_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clinic_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_members')),
    sa.UniqueConstraint('clinic_id', 'user_id', name=op.f('uq_clinic_members_clinic_id'))
    )
    op.create_index(op.f('ix_clinic_members_clinic_id'), 'clinic_members', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_members_user_id'), 'clinic_members', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_conversations_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_conversations_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_clinic_patient_id'), 'conversations', ['clinic_patient_id'], unique=False)
    op.create_index(op.f('ix_conversations_physio_user_id'), 'conversations', ['physio_user_id'], unique=False)
    op.create_table('exercise_media',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('video', 'image', name='mediakind', native_enum=False, length=24), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_media_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_media'))
    )
    op.create_index(op.f('ix_exercise_media_exercise_id'), 'exercise_media', ['exercise_id'], unique=False)
    op.create_table('exercise_translations',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cues', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_translations_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_translations')),
    sa.UniqueConstraint('exercise_id', 'locale', name=op.f('uq_exercise_translations_exercise_id'))
    )
    op.create_table('invoices',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'due', 'paid', 'void', name='invoicestatus', native_enum=False, length=24), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('tax_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('paid_via', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_branch_id_branches')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_invoices_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_invoices_clinic_patient_id_clinic_patients')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_invoices_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('clinic_id', 'number', name=op.f('uq_invoices_clinic_id'))
    )
    op.create_index(op.f('ix_invoices_clinic_id'), 'invoices', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_invoices_clinic_patient_id'), 'invoices', ['clinic_patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('medical_backgrounds',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('past_history', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('prior_medicines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('core_grade', sa.Enum('poor', 'fair', 'good', 'strong', name='coregrade', native_enum=False, length=24), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_medical_backgrounds_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_backgrounds')),
    sa.UniqueConstraint('clinic_patient_id', name=op.f('uq_medical_backgrounds_clinic_patient_id'))
    )
    op.create_table('queue_tokens',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('physio_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'serving', 'done', 'skipped', name='tokenstatus', native_enum=False, length=24), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_queue_tokens_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_queue_tokens_patient_id_patients')),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_queue_tokens_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_tokens')),
    sa.UniqueConstraint('branch_id', 'service_date', 'number', name=op.f('uq_queue_tokens_branch_id'))
    )
    op.create_index(op.f('ix_queue_tokens_status'), 'queue_tokens', ['status'], unique=False)
    op.create_table('attendance',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'half_day', 'on_leave', 'absent', name='attendancestatus', native_enum=False, length=24), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['clinic_members.id'], name=op.f('fk_attendance_member_id_clinic_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('member_id', 'day', name=op.f('uq_attendance_member_id'))
    )
    op.create_index(op.f('ix_attendance_day'), 'attendance', ['day'], unique=False)
    op.create_table('care_plan_exercises',
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('sets', sa.SmallInteger(), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('hold_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'alternate_days', 'weekly_3x', 'weekly', name='frequency', native_enum=False, length=24), nullable=False),
    sa.Column('times_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_care_plan_exercises_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_care_plan_exercises_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_plan_exercises'))
    )
    op.create_index(op.f('ix_care_plan_exercises_care_plan_id'), 'care_plan_exercises', ['care_plan_id'], unique=False)
    op.create_table('consultations',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('care_plan_id', sa.UUID(), nullable=True),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pain_vas', sa.SmallInteger(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_consultations_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_consultations_care_plan_id_care_plans')),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_consultations_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_consultations_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index(op.f('ix_consultations_clinic_patient_id'), 'consultations', ['clinic_patient_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate_paise', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('casual', 'sick', 'earned', 'unpaid', name='leavetype', native_enum=False, length=24), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='leavestatus', native_enum=False, length=24), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_leave_requests_decided_by_users')),
    sa.ForeignKeyConstraint(['member_id'], ['clinic_members.id'], name=op.f('fk_leave_requests_member_id_clinic_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index(op.f('ix_leave_requests_member_id'), 'leave_requests', ['member_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('medications',
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dose', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('timing', sa.String(length=60), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('reminder_times', postgresql.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('starts_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_medications_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_care_plan_id'), 'medications', ['care_plan_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_messages_sender_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('payslips',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('gross_paise', sa.Integer(), nullable=False),
    sa.Column('deductions_paise', sa.Integer(), nullable=False),
    sa.Column('net_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='payslipstatus', native_enum=False, length=24), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_payslips_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['clinic_members.id'], name=op.f('fk_payslips_member_id_clinic_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('member_id', 'period', name=op.f('uq_payslips_member_id'))
    )
    op.create_index(op.f('ix_payslips_clinic_id'), 'payslips', ['clinic_id'], unique=False)
    op.create_table('reviews',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reviews_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_reviews_patient_id_patients')),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_reviews_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_reviews_appointment_id'))
    )
    op.create_index(op.f('ix_reviews_physio_user_id'), 'reviews', ['physio_user_id'], unique=False)
    op.create_table('test_orders',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=True),
    sa.Column('ordered_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ordered', 'result_ready', 'cancelled', name='testorderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('result_file_urls', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_test_orders_care_plan_id_care_plans')),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_test_orders_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], name=op.f('fk_test_orders_ordered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_orders'))
    )
    op.create_index(op.f('ix_test_orders_clinic_patient_id'), 'test_orders', ['clinic_patient_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('plan_exercise_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feel', sa.Enum('easy', 'ok', 'hard', name='feel', native_enum=False, length=24), nullable=True),
    sa.Column('pain', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_exercise_logs_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_exercise_id'], ['care_plan_exercises.id'], name=op.f('fk_exercise_logs_plan_exercise_id_care_plan_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_logs'))
    )
    op.create_index('ix_exercise_logs_patient_day', 'exercise_logs', ['patient_id', 'logged_on'], unique=False)
    op.create_table('medication_logs',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('dose_slot', sa.String(length=5), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_medication_logs_medication_id_medications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medication_logs_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_logs'))
    )
    op.create_index('ix_medication_logs_patient_day', 'medication_logs', ['patient_id', 'logged_on'], unique=False)
    op.create_table('prescriptions',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('physio_user_id', sa.UUID(), nullable=False),
    sa.Column('rx_no', sa.String(length=30), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_prescriptions_care_plan_id_care_plans')),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_prescriptions_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['physio_user_id'], ['users.id'], name=op.f('fk_prescriptions_physio_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions')),
    sa.UniqueConstraint('rx_no', name=op.f('uq_prescriptions_rx_no'))
    )
    op.create_index(op.f('ix_prescriptions_clinic_patient_id'), 'prescriptions', ['clinic_patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_clinic_patient_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_medication_logs_patient_day', table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index('ix_exercise_logs_patient_day', table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_test_orders_clinic_patient_id'), table_name='test_orders')
    op.drop_table('test_orders')
    op.drop_index(op.f('ix_reviews_physio_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payslips_clinic_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medications_care_plan_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_member_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_consultations_clinic_patient_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_care_plan_exercises_care_plan_id'), table_name='care_plan_exercises')
    op.drop_table('care_plan_exercises')
    op.drop_index(op.f('ix_attendance_day'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_queue_tokens_status'), table_name='queue_tokens')
    op.drop_table('queue_tokens')
    op.drop_table('medical_backgrounds')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_clinic_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_clinic_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('exercise_translations')
    op.drop_index(op.f('ix_exercise_media_exercise_id'), table_name='exercise_media')
    op.drop_table('exercise_media')
    op.drop_index(op.f('ix_conversations_physio_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_clinic_patient_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_clinic_members_user_id'), table_name='clinic_members')
    op.drop_index(op.f('ix_clinic_members_clinic_id'), table_name='clinic_members')
    op.drop_table('clinic_members')
    op.drop_index(op.f('ix_care_plans_status'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_clinic_patient_id'), table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_availabilities_physio_user_id'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('ix_appointments_physio_starts', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_points_ledger_patient_id'), table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_purpose'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_clinic_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_exercises_status'), table_name='exercises')
    op.drop_index('ix_exercises_search', table_name='exercises', postgresql_using='gin')
    op.drop_index(op.f('ix_exercises_owner_clinic_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_body_region'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_clinic_patients_patient_id'), table_name='clinic_patients')
    op.drop_index(op.f('ix_clinic_patients_clinic_id'), table_name='clinic_patients')
    op.drop_table('clinic_patients')
    op.drop_index(op.f('ix_branches_clinic_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_city'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_physio_profiles_verification_status'), table_name='physio_profiles')
    op.drop_table('physio_profiles')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_clinics_owner_user_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_requests_phone'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_table('health_tips')
    # ### end Alembic commands ###
