"""digital twin plan suggestions

Revision ID: 8cd3311c326e
Revises: b83f1db4dcfa
Create Date: 2026-09-28 23:27:40.394856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cd3311c326e'
down_revision: Union[str, Sequence[str], None] = 'b83f1db4dcfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_suggestions',
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=True),
    sa.Column('author', sa.Enum('rules', 'physio', 'ai', name='suggestionauthor', native_enum=False, length=24), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='suggestionstatus', native_enum=False, length=24), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('applied_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_plan_suggestions_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_plan_suggestions_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flag_id'], ['twin_flags.id'], name=op.f('fk_plan_suggestions_flag_id_twin_flags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_suggestions'))
    )
    op.create_index(op.f('ix_plan_suggestions_care_plan_id'), 'plan_suggestions', ['care_plan_id'], unique=False)
    op.create_index(op.f('ix_plan_suggestions_flag_id'), 'plan_suggestions', ['flag_id'], unique=False)
    op.create_index(op.f('ix_plan_suggestions_status'), 'plan_suggestions', ['status'], unique=False)
    op.create_index('uq_plan_suggestions_pending_flag', 'plan_suggestions', ['flag_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_plan_suggestions_pending_flag', table_name='plan_suggestions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_plan_suggestions_status'), table_name='plan_suggestions')
    op.drop_index(op.f('ix_plan_suggestions_flag_id'), table_name='plan_suggestions')
    op.drop_index(op.f('ix_plan_suggestions_care_plan_id'), table_name='plan_suggestions')
    op.drop_table('plan_suggestions')
    # ### end Alembic commands ###
