"""pilot leads

Revision ID: fcb3bbeb3ae0
Revises: 8380c314e541
Create Date: 2026-09-29 10:34:41.211250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb3bbeb3ae0'
down_revision: Union[str, Sequence[str], None] = '8380c314e541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_leads',
    sa.Column('clinic_name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('knee_patients_per_month', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_leads'))
    )
    op.create_index(op.f('ix_pilot_leads_created_at'), 'pilot_leads', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pilot_leads_created_at'), table_name='pilot_leads')
    op.drop_table('pilot_leads')
    # ### end Alembic commands ###
