"""digital twin flags

Revision ID: b83f1db4dcfa
Revises: 15916a980856
Create Date: 2026-09-28 23:14:48.708608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b83f1db4dcfa'
down_revision: Union[str, Sequence[str], None] = '15916a980856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twin_flags',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.Enum('info', 'watch', 'act', name='flagseverity', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'dismissed', name='flagstatus', native_enum=False, length=24), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clear_since', sa.Date(), nullable=True),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_twin_flags_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_twin_flags_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_twin_flags_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twin_flags'))
    )
    op.create_index(op.f('ix_twin_flags_care_plan_id'), 'twin_flags', ['care_plan_id'], unique=False)
    op.create_index(op.f('ix_twin_flags_clinic_patient_id'), 'twin_flags', ['clinic_patient_id'], unique=False)
    op.create_index(op.f('ix_twin_flags_status'), 'twin_flags', ['status'], unique=False)
    op.create_index('uq_twin_flags_active', 'twin_flags', ['care_plan_id', 'rule'], unique=True, postgresql_where=sa.text("status IN ('open', 'acknowledged')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_twin_flags_active', table_name='twin_flags', postgresql_where=sa.text("status IN ('open', 'acknowledged')"))
    op.drop_index(op.f('ix_twin_flags_status'), table_name='twin_flags')
    op.drop_index(op.f('ix_twin_flags_clinic_patient_id'), table_name='twin_flags')
    op.drop_index(op.f('ix_twin_flags_care_plan_id'), table_name='twin_flags')
    op.drop_table('twin_flags')
    # ### end Alembic commands ###
