"""whatsapp sessions and message log

Revision ID: dda6bfb497a4
Revises: f9b4f7cd3c65
Create Date: 2026-09-29 00:09:22.374284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dda6bfb497a4'
down_revision: Union[str, Sequence[str], None] = 'f9b4f7cd3c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_whatsapp_messages_patient_id_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_messages')),
    sa.UniqueConstraint('provider_id', name=op.f('uq_whatsapp_messages_provider_id'))
    )
    op.create_index(op.f('ix_whatsapp_messages_patient_id'), 'whatsapp_messages', ['patient_id'], unique=False)
    op.create_table('whatsapp_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('step', sa.String(length=20), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_whatsapp_sessions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_sessions')),
    sa.UniqueConstraint('patient_id', 'day', name=op.f('uq_whatsapp_sessions_patient_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_messages_patient_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
