"""clinic twin pilot switch

Revision ID: 77247b909afe
Revises: dda6bfb497a4
Create Date: 2026-09-29 00:22:31.968223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77247b909afe'
down_revision: Union[str, Sequence[str], None] = 'dda6bfb497a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('twin_pilot', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'twin_pilot')
    # ### end Alembic commands ###
