"""unique medication dose log

Revision ID: 937890fbc65d
Revises: 3ffadbea8bdf
Create Date: 2026-09-25 14:03:11.280949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937890fbc65d'
down_revision: Union[str, Sequence[str], None] = '3ffadbea8bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_medication_logs_dose', 'medication_logs', ['medication_id', 'logged_on', 'dose_slot'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_medication_logs_dose', 'medication_logs', type_='unique')
    # ### end Alembic commands ###
