"""camera validation pairs

Revision ID: f9b4f7cd3c65
Revises: 8cd3311c326e
Create Date: 2026-09-28 23:43:41.017548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b4f7cd3c65'
down_revision: Union[str, Sequence[str], None] = '8cd3311c326e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_pairs',
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('camera_measurement_id', sa.UUID(), nullable=False),
    sa.Column('reference_measurement_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('side', sa.Enum('left', 'right', 'none', name='side', native_enum=False, length=24), nullable=False),
    sa.Column('posture', sa.String(length=20), nullable=False),
    sa.Column('camera_value', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('camera_value_3d', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('reference_value', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('frames', sa.SmallInteger(), nullable=False),
    sa.Column('spread', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('fps', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('lighting', sa.String(length=20), nullable=True),
    sa.Column('clothing', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['camera_measurement_id'], ['measurements.id'], name=op.f('fk_validation_pairs_camera_measurement_id_measurements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_validation_pairs_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_validation_pairs_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_measurement_id'], ['measurements.id'], name=op.f('fk_validation_pairs_reference_measurement_id_measurements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_pairs'))
    )
    op.create_index(op.f('ix_validation_pairs_clinic_patient_id'), 'validation_pairs', ['clinic_patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_pairs_clinic_patient_id'), table_name='validation_pairs')
    op.drop_table('validation_pairs')
    # ### end Alembic commands ###
