"""booking holds and branch timezone

Revision ID: 3ffadbea8bdf
Revises: c5bb115cb21e
Create Date: 2026-09-25 13:31:33.159556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffadbea8bdf'
down_revision: Union[str, Sequence[str], None] = 'c5bb115cb21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('uq_appointments_physio_slot_live', 'appointments', ['physio_user_id', 'starts_at'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed', 'checked_in', 'completed')"))
    op.add_column('branches', sa.Column('timezone', sa.String(length=40), server_default='Asia/Kolkata', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'timezone')
    op.drop_index('uq_appointments_physio_slot_live', table_name='appointments', postgresql_where=sa.text("status IN ('pending', 'confirmed', 'checked_in', 'completed')"))
    op.drop_column('appointments', 'hold_expires_at')
    # ### end Alembic commands ###
