"""digital twin measurements and targets

Revision ID: ccb3628ef287
Revises: 3eeb02174168
Create Date: 2026-09-28 22:44:38.894025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb3628ef287'
down_revision: Union[str, Sequence[str], None] = '3eeb02174168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_plan_targets',
    sa.Column('care_plan_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('side', sa.Enum('left', 'right', 'none', name='side', native_enum=False, length=24), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('by_week', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_care_plan_targets_care_plan_id_care_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_plan_targets')),
    sa.UniqueConstraint('care_plan_id', 'code', 'side', name=op.f('uq_care_plan_targets_care_plan_id'))
    )
    op.create_index(op.f('ix_care_plan_targets_care_plan_id'), 'care_plan_targets', ['care_plan_id'], unique=False)
    op.create_table('measurements',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('clinic_patient_id', sa.UUID(), nullable=False),
    sa.Column('care_plan_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('side', sa.Enum('left', 'right', 'none', name='side', native_enum=False, length=24), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('source', sa.Enum('clinic', 'self', 'camera', name='measurementsource', native_enum=False, length=24), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], name=op.f('fk_measurements_care_plan_id_care_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_patient_id'], ['clinic_patients.id'], name=op.f('fk_measurements_clinic_patient_id_clinic_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_measurements_consultation_id_consultations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_measurements_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_measurements_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements'))
    )
    op.create_index(op.f('ix_measurements_clinic_patient_id'), 'measurements', ['clinic_patient_id'], unique=False)
    op.create_index('ix_measurements_patient_code_time', 'measurements', ['patient_id', 'code', 'measured_at'], unique=False)
    op.add_column('care_plans', sa.Column('protocol', sa.String(length=40), nullable=True))
    op.add_column('care_plans', sa.Column('surgery_date', sa.Date(), nullable=True))
    op.add_column('care_plans', sa.Column('affected_side', sa.Enum('left', 'right', 'both', name='affectedside', native_enum=False, length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_plans', 'affected_side')
    op.drop_column('care_plans', 'surgery_date')
    op.drop_column('care_plans', 'protocol')
    op.drop_index('ix_measurements_patient_code_time', table_name='measurements')
    op.drop_index(op.f('ix_measurements_clinic_patient_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_care_plan_targets_care_plan_id'), table_name='care_plan_targets')
    op.drop_table('care_plan_targets')
    # ### end Alembic commands ###
