"""clinic ai assist switch

Revision ID: 8380c314e541
Revises: 77247b909afe
Create Date: 2026-09-29 00:55:08.650058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8380c314e541'
down_revision: Union[str, Sequence[str], None] = '77247b909afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('ai_assist', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'ai_assist')
    # ### end Alembic commands ###
